### ISSUE TITLE
Managing observation and checklist data independently

### ISSUE THREAD

**Issue by mstrimas** [cboettig/birddb#2]
Many users will want to work with both the observation data (referred to as the eBird Basic Dataset) and the checklist data (referred to as the Sampling Event Data). We'll want to manage these two datasets. With my latest PR, `import_ebird()` can now import either textfile to parquet, however, at the moment they have the same destination.

One possibility would be to have `import_ebird_checklists()` and `import_ebird_observations()`, which import the data to parquet in directories `BIRDDB_HOME/checklists/` and `BIRDDB_HOME/observations/`, respectively. I suppose we'd then want `ebird_checklists()` and `ebird_observations()` to replace `ebird()`.

Many users will want to combine these two datasets together to produce presence absence data. Perhaps this is where the connection to `auk` could be valuable.

Also worth noting that almost the entire EBD is checklist level data duplicated for every observation on a checklist. There are only a small number (~5) of columns that are observation/species specific.

**Comment by cboettig** [comment]
Yeah, wanted to discuss the other datasets with you.  Just to make sure I'm up-to-speed on terminology: the "Sampling Event Data" is the one I've been using so far?  e.g. the file like `ebd_relJul-2021.txt.gz` I get from the archive?  If we can tell the observations from the checklist data apart by filename or file header, it may make the most sense to just have `import_ebird()` detect which is which automatically, and have the `ebird_parquet_files` fn (https://github.com/cboettig/birddb/blob/main/R/ebird_data_dir.R#L27) or whatnot set the parquet directory accordingly. 

I think there's a bunch of interesting things we can discuss about how best to present these tables.  From `duckdb`'s perspective, it's perfectly natural to consider these as multiple tables in a relational database (the RStudio connection pane will happily show the list of tables, along with previews, over the remote connection -- we can add a small wrapper plugin to deploy that pane automatically).  

Combining the two datasets sounds like some kind of join to me?  If so, it may make sense to pre-compute the table join as a `VIEW`, perhaps during the `import_ebird()` step.  (Certainly open to doing this by auk, but if it's a standard join doing it as a SQL operation will probably be faster, and we can store the pre-computed view).  

It sounds like we might want to do something of the reverse on the checklist data as well by 'un-joining' it, so there is there are separate tables for checklist and observation data?  Again I haven't really gotten acquainted with the data organization so I'm not totally clear on the precise operation involved, but sounds like something where we could again run some SQL to store some pre-computed VIEWs of the data that might speed up / facilitate a lot of user operations here... Let me know if any of this sounds useful / reasonable

**Comment by mstrimas** [comment]
Yeah, sorry, the naming is confusing. So far you've been using the eBird Basic Dataset (EBD) containing observation level data. The sampling event data contains checklist level data and filenames have a similar format: `ebd_sampling_elJul-2021.txt.gz`. Eventually I would like to normalize calling these files the observation and checklist data, respectively, and possibly calling the whole thing the EBD since that term has become very familiar to those using this dataset. Hopefully, if we do get an update to how these data are distributed, part of that can be a change of the currently naming scheme, especially because "sampling event data" is quite confusing. 

Two other important concepts to be familiar with here. First, "complete checklists", which are checklists where the user has specified that they're reporting all the species they encountered, hence we can assume that any species not reported has a count of zero. Second, data reported below the species level (e.g. recognizable forms or subspecies) need to be "rolled up" to species level prior filling in assumed zeros, which is made particularly annoying by the fact that a single checklist can have multiple subspecies of the same species (e.g. multiple Junco forms).

I think as a start just allowing users to import both these files to their own parquet files would be great! And, I think the approach you've outlined makes sense. Then we can begin the longer process of thinking through what additional functionality we'd want to add, a process which I expect will depend a lot on understanding how users typically use the data.

Internally, for our analyses, we subset everything to just complete checklists, roll up to species level, normalize the observation data to remove the duplicate checklist information, import both tables into a DB, and build indexes to speed up the join. Then, to use the data for a single species, we perform a left join of checklist to observation data, filling the missing counts in the observation data with zeros. For "super users", having the ability to set something like this up would be valuable, but for users just wanting a single species or who don't care about zero-filled data this is likely overkill (although I suppose we'd need to benchmark setting up the view/join to see if that is actually the case). In addition, given the time required to set up the `duckdb` views on the parquet files, and the view on the joined tables, it seems like for these super users it could make sense to just create a permanent `duckdb` file rather than having to set up the parquet views each time? This is essentially what we do for our internal analysis dataset. Anyway, I'll look at setting up the ability to import both files as a start.

**Comment by cboettig** [comment]
Thanks for explaining the structures, that makes sense and is super helpful.  Yup, all for standardizing the nomenclature as you describe.

So yeah, let's start just by importing each of these datasets as parquet files.  I like your idea of moving to your proposed nomenclature for the parquet files, i.e. having `parquet/observation/` dir and and a `parquet/checklist` dir for the  respective files. Certainly makes sense to allow users to access parquet files that are essentially the equivalent of the txt tables, in addition to any views.  (As you probably saw, we currently have to create a View just to see these in duckdb, though I think that won't always be true in the future, it's just a missing feature in the R client). 

We could scrap the `ebird()` fn in favor of `observation()` and `checklist()` functions.  as I mentioned, more experienced users could always view all tables with something like `ebird_conn() %>% DBI::dbListTables()`.  

> Internally, for our analyses, we subset everything to just complete checklists, roll up to species level, normalize the observation data to remove the duplicate checklist information, import both tables into a DB, and build indexes to speed up the join. Then, to use the data for a single species, we perform a left join of checklist to observation data, filling the missing counts in the observation data with zeros

Thanks, this sounds great.  Like you say, it probably makes sense to have this as a separate function to generate these views, rather than impose the computational overhead to do this on every user when the first do `import_ebird()`.  It sounds like we could literally execute your existing SQL to do this on duckdb.  

Right, we could store the pre-computed views.  Currently, if a user provides a path as `BIRDDB_DUCKDB`, it can be used for persistent storage of the views:
https://github.com/cboettig/birddb/blob/4815325d8bfceb1ecf61d15be767caae3f960f29/R/ebird_data_dir.R#L20-L25

but we could easily make that default to the BIRDDB_HOME instead of `:memory:` so persistence would be the default.
