### ISSUE TITLE
EBD versions

### ISSUE THREAD

**Issue by mstrimas** [cboettig/birddb#4]
The EBD is released monthly and it's valuable to keep track of which version of the data a user has. An easy approach would be to parse the version from the tar filename then include it as part of the `parquet/` directory name. One other thought would be to have a small metadata file in the `parquet/` directory storing the name of the file that generated that parquet file and the date that the data were imported. Do you have any thoughts on a better approach?

This also brings up the question of multiple data versions. Do we want to remove an old version of the EBD when a new one is imported? Keep multiple and allow users to specify the version they want somehow in `ebird()`? Always load the most recent version with `ebird()`?

Almost all users will only ever want a single version of the EBD at a time, but some may periodically download a newer version to get the most recent data.

**Comment by cboettig** [comment]
Yup, that's a good point. Like you say, a user will probably not want to start accumulating multiple versions, but definitely ought to be able to easily look up which version they were using.  Definitely support the idea of just writing a small metadata file to `BIRDDB_HOME` with the release version, and ideally the sha256 hash of the downloaded tarball (ideally we'd check hashes of downloaded objects against known values to ensure integrity, but at least recording this value is best practice since it gives a verifiable way to confirm the file is the one you think it is).  It may also be wise to record the date the metadata entry was generated, and perhaps the filesize of the tarball.  Perhaps adding a friendly `ebord_citation()` function would be the way a user could see a formatted citation, including the version currently in use.  

When a user downloads a new version, I think the default behavior should probably be to overwrite the old version, though with a `utils::AskYesNo()` confirmation before overwriting if R is in `interactive()` mode.  I imagine adding the new version would create a new entry in the metadata file, so a user could dig back if they like and see when they had the old version, but it would not keep the old version around. 

Note that a user intent on having two versions on the same machine could manage this already by explicitly setting `BIRDDB_HOME` to separate paths for each version.  We can document that, but it's probably an edge case.  I imagine most users won't ever set `BIRDDB_HOME`, though it's also useful if you're on a multi-user server and you don't want each user downloading and storing their own copy of eBird.
